# Generated by Django 3.1.8 on 2021-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
