# Generated by Django 3.1.8 on 2021-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20210506_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom_communaute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
