# Generated by Django 3.1.8 on 2021-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_auto_20210506_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pourcentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
